<a href="https://colab.research.google.com/github/sebastiancasas10/curso-ia-para-economia/blob/main/Taller_combinacion_y_exportacion_datos_Sebastian_Casas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Taller combinacion y exportacion datos**

Sebastián Casas Poloche

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

Establecer la ruta de los datasets

In [72]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [73]:
path =  '/content/drive/MyDrive/dataset_GEIH'

In [74]:
os.chdir(path)

**Datos** **de** **Julio**

In [75]:
df_caracteristicas_jul = pd.read_excel('JULIO/caracteristicas_julio.xlsx')
df_caracteristicas_jul.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27752874284,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27752874284,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,5911013206,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00

In [76]:
df_fuerza_jul = pd.read_excel('JULIO/fuerza_trabajo_julio.xlsx')
df_fuerza_jul.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250731,7,2025,8283143,1,1,1,50,NaN,2,27752874284,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250731,7,2025,8283143,1,2,1,50,NaN,2,27752874284,8,NaN,1.00,1,4,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,7,2025,8283145,1,1,1,50,NaN,2,5911013206,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df_hogar_jul = pd.read_excel('JULIO/hogar_julio.xlsx')
df_hogar_jul.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20250731,7,2025,8283143,1,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2
1,20250731,7,2025,8283145,1,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4
2,20250731,7,2025,8283147,1,1,1,NaN,2,57990161862,8,1,1,2,1,1.00,2,2,2,NaN,2,1,6,5,2,1.00,4,6,1,1.00,1,NaN,NaN,"30,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,7

In [78]:
df_ocupados_jul = pd.read_excel('JULIO/ocupados_julio.xlsx')
df_ocupados_jul.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,60,NaN,2,27752874284,8,1,143,1,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84,7,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,40,NaN,NaN,40,NaN,NaN,2,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,0.00,3.00,4.00,NaN,3.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,10.00,3,NaN,1,"790,000.00",1,143,9212
1,20250731,7,2025,8283145,1,1,1,60,NaN,2,5911013206,8,1,141,1,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48,1,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,70,NaN,NaN,70,NaN,NaN,2,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,1.00,36.00,7.00,NaN,7.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2,1,1,3,NaN,4.00,8,NaN,1,"1,100,000.00",1,141,1311
2,20250731,7,2025,8283145,1,3,1,60,NaN,2,5911013206,8,1,141,1,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48,7,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,60,NaN,NaN,60,NaN,NaN,2,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,1.00,18.00,7.00,NaN,8.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2,1,1,3,NaN,3.00,3,NaN,1,"820,000.00",1,141,9212

In [79]:
df_caracteristicas_jul.columns
df_hogar_jul.columns
df_fuerza_jul.columns
df_ocupados_jul.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=202)

**Unión base de datos**

In [80]:
base_julio = pd.merge(df_caracteristicas_jul, df_hogar_jul, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [81]:
base_julio = pd.merge(base_julio, df_fuerza_jul, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [82]:
df_ocupados_jul = df_ocupados_jul.drop(columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

In [85]:
df_ocupados_jul = df_ocupados_jul.drop(columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [86]:
base_julio = pd.merge(base_julio, df_ocupados_jul, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [87]:
base_julio.shape
base_julio.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27752874284,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00"
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27752874284,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,5911013206,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00"
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,5911013206,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,5911013206,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00"

**Datos de agosto**

In [88]:
df_caracteristicas_ago = pd.read_excel('AGOSTO/caracteristicas_agosto.xlsx')
df_caracteristicas_ago.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250835,8,2025,8316823,1,1,1,10,NaN,2,21338782805,8,1,1,1,64,6.00,"1,961.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,10.00,4.00,731.00,2.00,NaN,2.00,1.00,1.00
1,20250835,8,2025,8316823,1,2,1,10,NaN,2,21338782805,8,1,2,2,63,10.00,"1,961.00",2,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,1.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00
2,20250835,8,2025,8316824,1,1,1,10,NaN,2,21317266121,8,1,1,1,62,6.00,"1,963.00",1,3,NaN,3,NaN,2,2.00,2,5,NaN,NaN,1.00,1.00,2.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00

In [89]:
df_fuerza_ago = pd.read_excel('AGOSTO/fuerza_trabajo_agosto.xlsx')
df_fuerza_ago.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250835,8,2025,8316823,1,1,1,50,NaN,2,21338782805,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250835,8,2025,8316823,1,2,1,50,NaN,2,21338782805,8,NaN,1.00,1,4,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250835,8,2025,8316824,1,1,1,50,NaN,2,21317266121,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
df_hogar_ago = pd.read_excel('AGOSTO/hogar_agosto.xlsx')
df_hogar_ago.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20250835,8,2025,8316823,1,1,1,NaN,2,21338782805,8,1,1,4,1,0.00,2,2,2,NaN,2,1,3,1,2,1.00,4,2,3,4.00,1,NaN,NaN,"50,000,000.00","200,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2
1,20250835,8,2025,8316824,1,1,1,NaN,2,21317266121,8,1,1,2,1,0.00,2,2,2,NaN,2,1,2,1,2,1.00,4,2,1,4.00,4,NaN,NaN,NaN,"350,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2
2,20250835,8,2025,8316825,1,1,1,NaN,2,39311306212,8,1,1,2,1,0.00,2,2,2,NaN,2,1,4,3,2,1.00,4,2,1,1.00,1,NaN,NaN,"40,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4

In [91]:
df_ocupados_ago = pd.read_excel('AGOSTO/ocupados_agosto.xlsx')
df_ocupados_ago.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250835,8,2025,8316823,1,1,1,60,NaN,2,21338782805,8,1,4541,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"900,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"900,000.00",1.00,"10,800,000.00",3.00,NaN,3.00,2.00,12,40,NaN,NaN,40,NaN,NaN,1,1,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,1.00,48.00,1.00,NaN,3.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2,1,1,14,NaN,NaN,3,NaN,1,"900,000.00",45,4541,1420
1,20250835,8,2025,8316824,1,1,1,60,NaN,2,21317266121,8,1,6010,1,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,18,1,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"350,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,47,NaN,NaN,47,NaN,NaN,6,8,NaN,1,NaN,1,2.00,1.00,8.00,1,1,1,0.00,72.00,1.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,15.00,1,NaN,1,"1,773,500.00",60,6010,3521
2,20250835,8,2025,8316824,1,2,1,60,NaN,2,21317266121,8,1,9700,1,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,72,3,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,47,NaN,NaN,47,NaN,NaN,1,2,NaN,1,NaN,1,2.00,1.00,6.00,2,2,1,0.00,24.00,3.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,2,NaN,30.00,1,NaN,1,"1,723,500.00",97,9700,9111

**Unión de datos**

In [92]:
base_agosto = pd.merge(df_caracteristicas_ago, df_hogar_ago, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [93]:
base_agosto = pd.merge(base_agosto, df_fuerza_ago, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [94]:
df_ocupados_ago = df_ocupados_ago.drop(
    columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

df_ocupados_ago = df_ocupados_ago.drop(
    columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [95]:
base_agosto = pd.merge(base_agosto, df_ocupados_ago, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [96]:
base_agosto.shape
base_agosto.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250835,8,2025,8316823,1,1,1,10,NaN,2,21338782805,8,1,1,1,64,6.00,"1,961.00",1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,10.00,4.00,731.00,2.00,NaN,2.00,1.00,1.00,20250835,8,2025,1,1,NaN,2,21338782805,8,1,1,4,1,0.00,2,2,2,NaN,2,1,3,1,2,1.00,4,2,3,4.00,1,NaN,NaN,"50,000,000.00","200,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,"20,250,835.00",8.00,"2,025.00",1.00,50.00,NaN,2.00,"21,338,782,805.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,541.00",2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"900,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"900,000.00",1.00,"10,800,000.00",3.00,NaN,3.00,2.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,48.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,"900,000.00",45.00,"4,541.00","1,420.00"
1,20250835,8,2025,8316823,1,2,1,10,NaN,2,21338782805,8,1,2,2,63,10.00,"1,961.00",2,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,1.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,20250835,8,2025,1,1,NaN,2,21338782805,8,1,1,4,1,0.00,2,2,2,NaN,2,1,3,1,2,1.00,4,2,3,4.00,1,NaN,NaN,"50,000,000.00","200,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,"20,250,835.00",8.00,"2,025.00",1.00,50.00,NaN,2.00,"21,338,782,805.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250835,8,2025,8316824,1,1,1,10,NaN,2,21317266121,8,1,1,1,62,6.00,"1,963.00",1,3,NaN,3,NaN,2,2.00,2,5,NaN,NaN,1.00,1.00,2.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250835,8,2025,1,1,NaN,2,21317266121,8,1,1,2,1,0.00,2,2,2,NaN,2,1,2,1,2,1.00,4,2,1,4.00,4,NaN,NaN,NaN,"350,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,"20,250,835.00",8.00,"2,025.00",1.00,50.00,NaN,2.00,"21,317,266,121.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,010.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,18.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"350,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,6.00,8.00,NaN,1.00,NaN,1.00,2.00,1.00,8.00,1.00,1.00,1.00,0.00,72.00,1.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,15.00,1.00,NaN,1.00,"1,773,500.00",60.00,"6,010.00","3,521.00"
3,20250835,8,2025,8316824,1,2,1,10,NaN,2,21317266121,8,1,2,2,50,1.00,"1,975.00",2,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,1.00,1.00,1.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,20250835,8,2025,1,1,NaN,2,21317266121,8,1,1,2,1,0.00,2,2,2,NaN,2,1,2,1,2,1.00,4,2,1,4.00,4,NaN,NaN,NaN,"350,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2,"20,250,835.00",8.00,"2,025.00",1.00,50.00,NaN,2.00,"21,317,266,121.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9,700.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,72.00,3.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,47.00,NaN,NaN,47.00,NaN,NaN,1.00,2.00,NaN,1.00,NaN,1.00,2.00,1.00,6.00,2.00,2.00,1.00,0.00,24.00,3.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,2.00,NaN,30.00,1.00,NaN,1.00,"1,723,500.00",97.00,"9,700.00","9,111.00"
4,20250835,8,2025,8316825,1,1,1,10,NaN,2,39311306212,8,1,1,1,30,4.00,"1,995.00",1,1,4.00,2,NaN,1,NaN,1,5,NaN,NaN,1.00,1.00,2.00,1,1.00,1.00,"56,920.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,20250835,8,2025,1,1,NaN,2,39311306212,8,1,1,2,1,0.00,2,2,2,NaN,2,1,4,3,2,1.00,4,2,1,1.00,1,NaN,NaN,"40,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4,"20,250,835.00",8.00,"2,025.00",1.00,50.00,NaN,2.00,"39,311,306,212.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,312.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,108.00,1.00,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"1,360,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,50.00,NaN,NaN,7.00,7.00,NaN,1.00,NaN,1.00,1.00,1.00,9.00,1.00,1.00,1.00,0.00,24.00,4.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,40.00,8.00,NaN,1.00,"1,423,500.00",33.00,"3,312.00","7,127.00"

**Datos de septiembre**

In [97]:
df_caracteristicas_sep = pd.read_excel('SEPTIEMBRE/caracteristicas_septiembre.xlsx')
df_caracteristicas_sep.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250939,9,2025,8345569,1,1,1,10,NaN,2,26598435838,8,1,1,1,59,5.00,"1,966.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00
1,20250939,9,2025,8345569,1,2,1,10,NaN,2,26598435838,8,1,2,2,62,9.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,1.00,2.00,1.00
2,20250939,9,2025,8345570,1,1,1,10,NaN,2,54026350027,8,1,1,2,50,2.00,"1,975.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00

In [98]:
df_fuerza_sep = pd.read_excel('SEPTIEMBRE/fuerza_trabajo_septiembre.xlsx')
df_fuerza_sep.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250939,9,2025,8345569,1,1,1,50,NaN,2,26598435838,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250939,9,2025,8345569,1,2,1,50,NaN,2,26598435838,8,NaN,1.00,1,4,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250939,9,2025,8345570,1,1,1,50,NaN,2,54026350027,8,NaN,1.00,1,4,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df_hogar_sep = pd.read_excel('SEPTIEMBRE/hogar_septiembre.xlsx')
df_hogar_sep.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20250939,9,2025,8345569,1,1,1,NaN,2,26598435838,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2
1,20250939,9,2025,8345570,1,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4
2,20250939,9,2025,8345571,1,1,1,NaN,2,43734934091,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5

In [100]:
df_ocupados_sep = pd.read_excel('SEPTIEMBRE/ocupados_septiembre.xlsx')
df_ocupados_sep.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250939,9,2025,8345569,1,1,1,60,NaN,2,26598435838,8,1,113,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,000,000.00",12.00,0.00,0.00,"960,000.00",0.00,"200,000.00",0.00,0.00,0.00,0.00,1.00,"100,000.00",2.00,NaN,NaN,NaN,2.00,NaN,NaN,2.00,NaN,"500,000.00",1.00,"6,000,000.00",2.00,NaN,9.00,2.00,12,56,NaN,NaN,56,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,4.00,3,NaN,1,"500,000.00",1,113,6111
1,20250939,9,2025,8345570,1,2,1,60,NaN,2,54026350027,8,1,113,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,468,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,200,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,050,000.00",1.00,"12,600,000.00",3.00,NaN,9.00,2.00,12,70,NaN,NaN,70,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,15.00,3,NaN,1,"1,050,000.00",1,113,6111
2,20250939,9,2025,8345570,1,3,1,60,NaN,2,54026350027,8,1,220,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"300,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"300,000.00",1.00,"1,600,000.00",3.00,NaN,1.00,1.00,12,40,NaN,NaN,40,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,0.00,3.00,4.00,NaN,3.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,5.00,3,NaN,1,"300,000.00",2,220,6210

**Unión de datos**

In [101]:
base_septiembre = pd.merge(df_caracteristicas_sep, df_hogar_sep, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [102]:
base_septiembre = pd.merge(base_septiembre, df_fuerza_sep, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [103]:
df_ocupados_sep = df_ocupados_sep.drop(columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

df_ocupados_sep = df_ocupados_sep.drop(columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [104]:
base_septiembre = pd.merge(base_septiembre,df_ocupados_sep, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [105]:
base_septiembre.shape
base_septiembre.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250939,9,2025,8345569,1,1,1,10,NaN,2,26598435838,8,1,1,1,59,5.00,"1,966.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,26598435838,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"26,598,435,838.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,000,000.00",12.00,0.00,0.00,"960,000.00",0.00,"200,000.00",0.00,0.00,0.00,0.00,1.00,"100,000.00",2.00,NaN,NaN,NaN,2.00,NaN,NaN,2.00,NaN,"500,000.00",1.00,"6,000,000.00",2.00,NaN,9.00,2.00,12.00,56.00,NaN,NaN,56.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,3.00,NaN,1.00,"500,000.00",1.00,113.00,"6,111.00"
1,20250939,9,2025,8345569,1,2,1,10,NaN,2,26598435838,8,1,2,2,62,9.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,1.00,2.00,1.00,20250939,9,2025,1,1,NaN,2,26598435838,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"26,598,435,838.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250939,9,2025,8345570,1,1,1,10,NaN,2,54026350027,8,1,1,2,50,2.00,"1,975.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250939,9,2025,8345570,1,2,1,10,NaN,2,54026350027,8,1,2,1,63,4.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,468.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,200,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,050,000.00",1.00,"12,600,000.00",3.00,NaN,9.00,2.00,12.00,70.00,NaN,NaN,70.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,15.00,3.00,NaN,1.00,"1,050,000.00",1.00,113.00,"6,111.00"
4,20250939,9,2025,8345570,1,3,1,10,NaN,2,54026350027,8,1,3,1,19,10.00,"2,005.00",3,1,1.00,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"300,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"300,000.00",1.00,"1,600,000.00",3.00,NaN,1.00,1.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"300,000.00",2.00,220.00,"6,210.00"

**Datos de octubre**

In [106]:
df_caracteristicas_oct = pd.read_excel('OCTUBRE/caracteristicas_octubre.xlsx')
df_caracteristicas_oct.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20251044,10,2025,8374095,1,1,1,10,NaN,2,3609714248,8,1,1,2,34,9.00,"1,991.00",1,2,NaN,2,NaN,2,2.00,2,6,NaN,NaN,2.00,1.00,2.00,1,1.00,1.00,"40,000.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,2.00,416.00,5.00,416.00,1.00,2.00,1.00
1,20251044,10,2025,8374095,1,2,1,10,NaN,2,3609714248,8,1,2,1,30,10.00,"1,995.00",2,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00
2,20251044,10,2025,8374095,1,3,1,10,NaN,2,3609714248,8,1,3,1,7,2.00,"2,018.00",3,1,1.00,2,NaN,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,1.00,5.00,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df_fuerza_oct = pd.read_excel('OCTUBRE/fuerza_trabajo_octubre.xlsx')
df_fuerza_oct.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20251044,10,2025,8374095,1,1,1,50,NaN,2,3609714248,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20251044,10,2025,8374095,1,2,1,50,NaN,2,3609714248,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20251044,10,2025,8374096,1,1,1,50,NaN,2,20425814514,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
df_hogar_oct = pd.read_excel('OCTUBRE/hogar_octubre.xlsx')
df_hogar_oct.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20251044,10,2025,8374095,1,1,1,NaN,2,3609714248,8,1,1,2,1,2.00,1,1,1,3.00,1,1,4,2,1,1.00,1,1,1,1.00,2,NaN,"530,000.00","180,000,000.00","150,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,3
1,20251044,10,2025,8374096,1,1,1,NaN,2,20425814514,8,1,1,2,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,2,NaN,"800,000.00","19,000,000.00","800,000.00",NaN,NaN,1.00,NaN,1.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,6
2,20251044,10,2025,8374097,1,1,1,NaN,2,32408368672,8,1,1,2,1,2.00,1,1,1,3.00,1,1,4,1,1,1.00,1,1,1,3.00,4,NaN,NaN,NaN,"850,000.00",NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [109]:
df_ocupados_oct = pd.read_excel('OCTUBRE/ocupados_octubre.xlsx')
df_ocupados_oct.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251044,10,2025,8374095,1,1,1,60,NaN,2,3609714248,8,1,6512,1,2.00,2.00,4.00,2.00,1.00,1.00,"7,810.00",1.00,1.00,1.00,1.00,3,1,NaN,1.00,1.00,1.00,1.00,6.00,1.00,"2,000,000.00",2.00,NaN,1.00,"100,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"160,000.00",1.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"500,000.00",2.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,42,NaN,NaN,42,NaN,NaN,10,7,NaN,1,NaN,1,1.00,1.00,15.00,1,1,1,6.00,3.00,1.00,NaN,9.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,1,1.00,1.00,1.00,1.00,2.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,1,2,2,2,2,2,11,NaN,30.00,10,TRABAJO INDEPENDIENTE,1,"2,000,000.00",65,6512,3321
1,20251044,10,2025,8374095,1,2,1,60,NaN,2,3609714248,8,1,145,1,2.00,2.00,2.00,1.00,NaN,1.00,NaN,2.00,1.00,1.00,1.00,1,1,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"1,423,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"20,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,7,8,NaN,1,NaN,1,1.00,1.00,0.00,1,1,1,0.00,24.00,4.00,NaN,8.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,1,2.00,1.00,1.00,2.00,2.00,1.00,2.00,2.00,2.00,NaN,2.00,1.00,1,1,1,2,2,1,11,NaN,60.00,5,NaN,1,"1,423,500.00",1,145,6122
2,20251044,10,2025,8374096,1,1,1,60,NaN,2,20425814514,8,1,4771,1,2.00,2.00,12.00,1.00,NaN,1.00,NaN,1.00,2.00,1.00,1.00,108,1,NaN,1.00,1.00,1.00,1.00,1.00,2.00,"2,023,500.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",2.00,1.00,"126,000.00",2.00,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"600,000.00",1.00,1.00,"1,361,500.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,10,7,NaN,1,NaN,1,1.00,1.00,12.00,1,1,1,2.00,36.00,1.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,11,NaN,35.00,3,NaN,1,"2,023,500.00",47,4771,1420

**Unión de bases**

In [110]:
base_octubre = pd.merge(df_caracteristicas_oct, df_hogar_oct, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [111]:
base_octubre = pd.merge( base_octubre, df_fuerza_oct, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [112]:
df_ocupados_oct = df_ocupados_oct.drop(columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

df_ocupados_oct = df_ocupados_oct.drop(columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [113]:
base_octubre = pd.merge( base_octubre, df_ocupados_oct, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [114]:
base_septiembre.shape
base_septiembre.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250939,9,2025,8345569,1,1,1,10,NaN,2,26598435838,8,1,1,1,59,5.00,"1,966.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,4.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,26598435838,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"26,598,435,838.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,000,000.00",12.00,0.00,0.00,"960,000.00",0.00,"200,000.00",0.00,0.00,0.00,0.00,1.00,"100,000.00",2.00,NaN,NaN,NaN,2.00,NaN,NaN,2.00,NaN,"500,000.00",1.00,"6,000,000.00",2.00,NaN,9.00,2.00,12.00,56.00,NaN,NaN,56.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,3.00,NaN,1.00,"500,000.00",1.00,113.00,"6,111.00"
1,20250939,9,2025,8345569,1,2,1,10,NaN,2,26598435838,8,1,2,2,62,9.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,1.00,2.00,1.00,20250939,9,2025,1,1,NaN,2,26598435838,8,1,5,1,1,0.00,2,2,2,NaN,2,1,1,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"26,598,435,838.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250939,9,2025,8345570,1,1,1,10,NaN,2,54026350027,8,1,1,2,50,2.00,"1,975.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250939,9,2025,8345570,1,2,1,10,NaN,2,54026350027,8,1,2,1,63,4.00,"1,962.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,468.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,200,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,050,000.00",1.00,"12,600,000.00",3.00,NaN,9.00,2.00,12.00,70.00,NaN,NaN,70.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,15.00,3.00,NaN,1.00,"1,050,000.00",1.00,113.00,"6,111.00"
4,20250939,9,2025,8345570,1,3,1,10,NaN,2,54026350027,8,1,3,1,19,10.00,"2,005.00",3,1,1.00,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,20250939,9,2025,1,1,NaN,2,54026350027,8,1,7,1,1,0.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,939.00",9.00,"2,025.00",1.00,50.00,NaN,2.00,"54,026,350,027.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"300,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"300,000.00",1.00,"1,600,000.00",3.00,NaN,1.00,1.00,12.00,40.00,NaN,NaN,40.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,5.00,3.00,NaN,1.00,"300,000.00",2.00,220.00,"6,210.00"

**Datos** **de noviembre**

In [115]:
df_caracteristicas_nov = pd.read_excel('NOVIEMBRE/caracteristicas_noviembre.xlsx')
df_caracteristicas_nov.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20251148,11,2025,8403077,1,1,1,10,NaN,2,50163641946,8,1,1,1,42,12.00,"1,982.00",1,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,4.00,NaN,NaN,NaN,2.00,1.00,1.00
1,20251148,11,2025,8403079,1,1,1,10,NaN,2,50163641946,8,1,1,1,38,8.00,"1,987.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00
2,20251148,11,2025,8403081,1,1,1,10,NaN,2,67999660447,8,1,1,1,45,11.00,"1,980.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00

In [116]:
df_fuerza_nov = pd.read_excel('NOVIEMBRE/fuerza_trabajo_noviembre.xlsx')
df_fuerza_nov.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20251148,11,2025,8403077,1,1,1,50,NaN,2,50163641946,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20251148,11,2025,8403079,1,1,1,50,NaN,2,50163641946,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20251148,11,2025,8403081,1,1,1,50,NaN,2,67999660447,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
df_hogar_nov = pd.read_excel('NOVIEMBRE/hogar_noviembre.xlsx')
df_hogar_nov.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20251148,11,2025,8403077,1,1,1,NaN,2,50163641946,8,1,1,4,1,1.00,1,2,2,NaN,2,1,2,1,2,1.00,4,3,6,NaN,4,NaN,NaN,NaN,"50,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,20251148,11,2025,8403079,1,1,1,NaN,2,50163641946,8,1,1,4,1,1.00,2,2,2,NaN,2,1,3,1,2,1.00,4,3,1,1.00,4,NaN,NaN,NaN,"400,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1
2,20251148,11,2025,8403081,1,1,1,NaN,2,67999660447,8,1,1,2,1,1.00,1,2,2,NaN,2,1,3,2,2,1.00,4,9,1,3.00,5,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5

In [118]:
df_ocupados_nov = pd.read_excel('NOVIEMBRE/ocupados_noviembre.xlsx')
df_ocupados_nov.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251148,11,2025,8403077,1,1,1,60,NaN,2,50163641946,8,1,4651,1,2.00,1.00,NaN,1.00,NaN,1.00,NaN,2.00,2.00,1.00,2.00,24,1,NaN,1.00,1.00,9.00,1.00,1.00,2.00,"1,600,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",1.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,8,8,NaN,1,NaN,1,1.00,1.00,2.00,1,1,1,0.00,156.00,3.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,3,NaN,30.00,1,NaN,1,"1,600,000.00",46,4651,5414
1,20251148,11,2025,8403079,1,1,1,60,NaN,2,50163641946,8,1,145,1,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,15,7,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"400,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,50,NaN,NaN,50,NaN,NaN,2,1,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,12.00,24.00,7.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,1,2.00,1.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,NaN,2.00,1.00,1,1,1,2,2,1,14,NaN,NaN,3,NaN,1,"800,000.00",1,145,6122
2,20251148,11,2025,8403081,1,1,1,60,NaN,2,67999660447,8,1,144,1,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,120,7,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"800,000.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,48,NaN,NaN,48,NaN,NaN,4,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,11,NaN,15.00,3,NaN,1,"1,100,000.00",1,144,9212

**Unión de bases**

In [123]:
base_noviembre = pd.merge( df_caracteristicas_nov, df_hogar_nov, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [124]:
base_noviembre = pd.merge( base_noviembre, df_fuerza_nov, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [125]:
df_ocupados_nov = df_ocupados_nov.drop(columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

df_ocupados_nov = df_ocupados_nov.drop(columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [126]:
base_noviembre = pd.merge( base_noviembre, df_ocupados_nov,on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [127]:
base_noviembre.shape
base_noviembre.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251148,11,2025,8403077,1,1,1,10,NaN,2,50163641946,8,1,1,1,42,12.00,"1,982.00",1,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,1.00,1.00,"56,940.00",4,4,4,4,4,4,4,4,1.00,2.00,NaN,4.00,4.00,NaN,NaN,NaN,2.00,1.00,1.00,20251148,11,2025,1,1,NaN,2,50163641946,8,1,1,4,1,1.00,1,2,2,NaN,2,1,2,1,2,1.00,4,3,6,NaN,4,NaN,NaN,NaN,"50,000.00",NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"20,251,148.00",11.00,"2,025.00",1.00,50.00,NaN,2.00,"50,163,641,946.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,651.00",1.00,2.00,1.00,NaN,1.00,NaN,1.00,NaN,2.00,2.00,1.00,2.00,24.00,1.00,NaN,1.00,1.00,9.00,1.00,1.00,2.00,"1,600,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,1.00,"200,000.00",1.00,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,"800,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,8.00,8.00,NaN,1.00,NaN,1.00,1.00,1.00,2.00,1.00,1.00,1.00,0.00,156.00,3.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,30.00,1.00,NaN,1.00,"1,600,000.00",46.00,"4,651.00","5,414.00"
1,20251148,11,2025,8403079,1,1,1,10,NaN,2,50163641946,8,1,1,1,38,8.00,"1,987.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20251148,11,2025,1,1,NaN,2,50163641946,8,1,1,4,1,1.00,2,2,2,NaN,2,1,3,1,2,1.00,4,3,1,1.00,4,NaN,NaN,NaN,"400,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1,"20,251,148.00",11.00,"2,025.00",1.00,50.00,NaN,2.00,"50,163,641,946.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,15.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"400,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"400,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,50.00,NaN,NaN,50.00,NaN,NaN,2.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,12.00,24.00,7.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,NaN,2.00,1.00,1.00,1.00,1.00,2.00,2.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,"800,000.00",1.00,145.00,"6,122.00"
2,20251148,11,2025,8403081,1,1,1,10,NaN,2,67999660447,8,1,1,1,45,11.00,"1,980.00",1,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,3.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20251148,11,2025,1,1,NaN,2,67999660447,8,1,1,2,1,1.00,1,2,2,NaN,2,1,3,2,2,1.00,4,9,1,3.00,5,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5,"20,251,148.00",11.00,"2,025.00",1.00,50.00,NaN,2.00,"67,999,660,447.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,120.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"800,000.00",2.00,NaN,2.00,NaN,NaN,1.00,"300,000.00",2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,48.00,NaN,NaN,48.00,NaN,NaN,4.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,11.00,NaN,15.00,3.00,NaN,1.00,"1,100,000.00",1.00,144.00,"9,212.00"
3,20251148,11,2025,8403081,1,2,1,10,NaN,2,67999660447,8,1,2,2,45,7.00,"1,980.00",2,2,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,1.00,2.00,1.00,20251148,11,2025,1,1,NaN,2,67999660447,8,1,1,2,1,1.00,1,2,2,NaN,2,1,3,2,2,1.00,4,9,1,3.00,5,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5,"20,251,148.00",11.00,"2,025.00",1.00,50.00,NaN,2.00,"67,999,660,447.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20251148,11,2025,8403081,1,3,1,10,NaN,2,67999660447,8,1,2,1,8,8.00,"2,017.00",3,1,2.00,1,1.00,1,NaN,1,6,NaN,NaN,NaN,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,1.00,1.00,3.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,20251148,11,2025,1,1,NaN,2,67999660447,8,1,1,2,1,1.00,1,2,2,NaN,2,1,3,2,2,1.00,4,9,1,3.00,5,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Datos de diciembre**

In [128]:
df_caracteristicas_dic = pd.read_excel('DICIEMBRE/caracteristicas_diciembre.xlsx')
df_caracteristicas_dic.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20251252,12,2025,8435963,1,1,1,10,NaN,2,10166138327,8,1,1,1,32,6.00,"1,993.00",1,2,NaN,3,NaN,1,NaN,1,1,820_01,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00
1,20251252,12,2025,8435963,1,2,1,10,NaN,2,10166138327,8,1,2,2,28,11.00,"1,997.00",2,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,419.00,5.00,419.00,1.00,2.00,1.00
2,20251252,12,2025,8435963,1,3,1,10,NaN,2,10166138327,8,1,2,1,0,5.00,"2,025.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
df_fuerza_dic = pd.read_excel('DICIEMBRE/fuerza_trabajo_diciembre.xlsx')
df_fuerza_dic.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20251252,12,2025,8435963,1,1,1,50,NaN,2,10166138327,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20251252,12,2025,8435963,1,2,1,50,NaN,2,10166138327,8,1.00,NaN,1,4,NaN,NaN,2.00,2.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20251252,12,2025,8435964,1,1,1,50,NaN,2,78402590074,8,1.00,NaN,1,1,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
df_hogar_dic = pd.read_excel('DICIEMBRE/hogar_diciembre.xlsx')
df_hogar_dic.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008
0,20251252,12,2025,8435963,1,1,1,NaN,2,10166138327,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,5,1.00,2,9,4,4.00,1,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3
1,20251252,12,2025,8435964,1,1,1,NaN,2,78402590074,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,6,NaN,2,9,1,4.00,1,NaN,NaN,"500,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1
2,20251252,12,2025,8435965,1,1,1,NaN,2,78402590074,8,1,5,1,2,NaN,2,2,2,NaN,2,1,1,1,6,NaN,2,9,2,4.00,5,NaN,NaN,NaN,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1

In [131]:
df_ocupados_dic = pd.read_excel('DICIEMBRE/ocupados_diciembre.xlsx')
df_ocupados_dic.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251252,12,2025,8435963,1,1,1,60,NaN,2,10166138327,8,1,311,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,204,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,800,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,200,000.00",1.00,"10,000,000.00",3.00,NaN,1.00,1.00,9,90,NaN,NaN,90,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,8.00,2.00,1.00,NaN,1.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20.00,2.00,1.00,1,2.00,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1,2,1,2,2,1,9,NaN,5.00,8,NaN,1,"1,200,000.00",3,311,6223
1,20251252,12,2025,8435963,1,2,1,60,NaN,2,10166138327,8,1,5611,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,56,NaN,NaN,56,NaN,NaN,2,7,NaN,2,NaN,2,NaN,NaN,NaN,2,2,1,18.00,24.00,1.00,NaN,9.00,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2,2,1,11,NaN,20.00,3,NaN,1,NaN,56,5611,9412
2,20251252,12,2025,8435964,1,1,1,60,NaN,2,78402590074,8,1,311,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"2,000,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,500,000.00",1.00,"12,000,000.00",3.00,NaN,3.00,2.00,12,54,NaN,NaN,54,NaN,NaN,1,8,NaN,2,NaN,2,NaN,NaN,NaN,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,1,35.00,"5,223.00","4,711.00",4.00,"500,000.00",1.00,1.00,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,2,1,1,9,NaN,30.00,3,NaN,1,"2,000,000.00",3,311,6222

**Unión de bases**

In [132]:
base_diciembre = pd.merge( df_caracteristicas_dic, df_hogar_dic, on=["DIRECTORIO","SECUENCIA_P"],
    how="left")

In [133]:
base_diciembre = pd.merge( base_diciembre, df_fuerza_dic, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [134]:
df_ocupados_dic = df_ocupados_dic.drop( columns=["PERIODO","MES","PER","HOGAR","REGIS","AREA","CLASE"],
    errors="ignore")

df_ocupados_dic = df_ocupados_dic.drop( columns=["FEX_C18","DPTO","FT"],
    errors="ignore")

In [135]:
base_diciembre = pd.merge( base_diciembre, df_ocupados_dic, on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
    how="left")

In [136]:
base_diciembre.shape
base_diciembre.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20251252,12,2025,8435963,1,1,1,10,NaN,2,10166138327,8,1,1,1,32,6.00,"1,993.00",1,2,NaN,3,NaN,1,NaN,1,1,820_01,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,5.00,2.00,NaN,2.00,NaN,2.00,1.00,1.00,20251252,12,2025,1,1,NaN,2,10166138327,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,5,1.00,2,9,4,4.00,1,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3,"20,251,252.00",12.00,"2,025.00",1.00,50.00,NaN,2.00,"10,166,138,327.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,204.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"1,800,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,200,000.00",1.00,"10,000,000.00",3.00,NaN,1.00,1.00,9.00,90.00,NaN,NaN,90.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,8.00,2.00,1.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,20.00,2.00,1.00,1.00,2.00,1.00,2.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,1.00,9.00,NaN,5.00,8.00,NaN,1.00,"1,200,000.00",3.00,311.00,"6,223.00"
1,20251252,12,2025,8435963,1,2,1,10,NaN,2,10166138327,8,1,2,2,28,11.00,"1,997.00",2,2,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,8.00,4.00,419.00,5.00,419.00,1.00,2.00,1.00,20251252,12,2025,1,1,NaN,2,10166138327,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,5,1.00,2,9,4,4.00,1,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3,"20,251,252.00",12.00,"2,025.00",1.00,50.00,NaN,2.00,"10,166,138,327.00",8.00,1.00,NaN,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5,611.00",2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,6.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,56.00,NaN,NaN,56.00,NaN,NaN,2.00,7.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,18.00,24.00,1.00,NaN,9.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,2.00,1.00,11.00,NaN,20.00,3.00,NaN,1.00,NaN,56.00,"5,611.00","9,412.00"
2,20251252,12,2025,8435963,1,3,1,10,NaN,2,10166138327,8,1,2,1,0,5.00,"2,025.00",3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,NaN,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20251252,12,2025,1,1,NaN,2,10166138327,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,5,1.00,2,9,4,4.00,1,NaN,NaN,"50,000,000.00","300,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20251252,12,2025,8435964,1,1,1,10,NaN,2,78402590074,8,1,1,1,75,8.00,"1,950.00",1,3,NaN,3,NaN,2,2.00,2,5,NaN,NaN,2.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20251252,12,2025,1,1,NaN,2,78402590074,8,1,5,1,2,NaN,2,2,2,NaN,2,1,2,1,6,NaN,2,9,1,4.00,1,NaN,NaN,"500,000,000.00","200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1,"20,251,252.00",12.00,"2,025.00",1.00,50.00,NaN,2.00,"78,402,590,074.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,2.00,1.00,1.00,1.00,6.00,NaN,NaN,"2,000,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,500,000.00",1.00,"12,000,000.00",3.00,NaN,3.00,2.00,12.00,54.00,NaN,NaN,54.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,35.00,"5,223.00","4,711.00",4.00,"500,000.00",1.00,1.00,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,9.00,NaN,30.00,3.00,NaN,1.00,"2,000,000.00",3.00,311.00,"6,222.00"
4,20251252,12,2025,8435965,1,1,1,10,NaN,2,78402590074,8,1,1,1,68,11.00,"1,957.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,4.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,5.00,NaN,NaN,NaN,2.00,1.00,1.00,20251252,12,2025,1,1,NaN,2,78402590074,8,1,5,1,2,NaN,2,2,2,NaN,2,1,1,1,6,NaN,2,9,2,4.00,5,NaN,NaN,NaN,"50,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1,"20,251,252.00",12.00,"2,025.00",1.00,50.00,NaN,2.00,"78,402,590,074.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,311.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,"2,400,000.00",1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,"1,800,000.00",1.00,"19,600,000.00",3.00,NaN,9.00,2.00,12.00,48.00,NaN,NaN,48.00,NaN,NaN,1.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,9.00,NaN,25.00,3.00,NaN,1.00,"1,800,000.00",3.00,311.00,"6,222.00"

**Unión de la base 2025**

In [137]:
base_2025 = pd.concat([base_julio, base_agosto, base_septiembre, base_octubre,
    base_noviembre, base_diciembre], ignore_index=True)

In [138]:
base_2025.shape

(409127, 330)

In [139]:
base_2025.head()

,PERIODO_x,MES_x,PER_x,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR_x,REGIS_x,AREA_x,CLASE_x,FEX_C18_x,DPTO_x,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27752874284,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00"
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27752874284,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,5911013206,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00"
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,5911013206,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,5911013206,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00"

In [148]:
base_2025 = base_2025.rename(columns={'PERIODO_x':'PERIODO','MES_x':'MES',
    'PER_x':'PER','HOGAR_x':'HOGAR','REGIS_x':'REGIS','AREA_x':'AREA',
    'CLASE_x':'CLASE','FEX_C18_x':'FEX_C18','DPTO_x':'DPTO'})

In [149]:
base_2025.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE',
       ...
       'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO', 'RAMA2D_R4',
       'RAMA4D_R4', 'OFICIO_C8', 'DESCRIPCION_CIIU'],
      dtype='object', length=331)

In [151]:
base_2025.head()

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,PERIODO,MES,PER,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,DESCRIPCION_CIIU
0,20250731,7,2025,8283143,1,1,1,10,NaN,2,27752874284,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00",Cría de ovejas y cabras
1,20250731,7,2025,8283143,1,2,1,10,NaN,2,27752874284,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27752874284,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"27,752,874,284.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,7,2025,8283145,1,1,1,10,NaN,2,5911013206,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00",Cría de ganado bovino y bufalino
3,20250731,7,2025,8283145,1,2,1,10,NaN,2,5911013206,8,1,2,2,50,2.00,"1,975.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250731,7,2025,8283145,1,3,1,10,NaN,2,5911013206,8,1,3,1,19,6.00,"2,006.00",3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,5911013206,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,"20,250,731.00",7.00,"2,025.00",1.00,50.00,NaN,2.00,"5,911,013,206.00",8.00,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"720,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,"820,000.00",1.00,141.00,"9,212.00",Cría de ganado bovino y bufalino

**Descripción del CIIU**

In [152]:
ciiu = pd.read_excel('/content/drive/MyDrive/dataset_GEIH/2025-01-14 Correlativa CIIU Rev4.xlsx',
                     sheet_name='CIIU 2022')

In [153]:
ciiu.columns

Index(['RAMA4D_R4', 'DESCRIPCION_CIIU'], dtype='object')

In [154]:
ciiu.head()

   RAMA4D_R4              DESCRIPCION_CIIU
0          0                   Desconocido
1         10  Actividad Personas Naturales
2         20  Actividad Personas Naturales
3         81  Actividad Personas Naturales
4         82  Actividad Personas Naturales

In [155]:
ciiu = ciiu[['RAMA4D_R4','DESCRIPCION_CIIU']]

In [156]:
base_2025 = pd.merge(base_2025, ciiu, on='RAMA4D_R4', how='left')

In [163]:
base_2025 = base_2025.drop(columns=['DESCRIPCION_CIIU_y'])

In [164]:
base_2025 = base_2025.rename(columns={'DESCRIPCION_CIIU_x':'DESCRIPCION_CIIU'})

In [165]:
base_2025[['RAMA4D_R4','DESCRIPCION_CIIU']].head()

   RAMA4D_R4                  DESCRIPCION_CIIU
0     143.00           Cría de ovejas y cabras
1        NaN                               NaN
2     141.00  Cría de ganado bovino y bufalino
3        NaN                               NaN
4     141.00  Cría de ganado bovino y bufalino

**Archivo Divipola**

In [171]:
divipola = pd.read_excel( '/content/drive/MyDrive/dataset_GEIH/2025-01-14 DIVIPOLA.xlsx',
    sheet_name='Departamentos', skiprows=8)

In [172]:
divipola.head()
divipola.columns

Index(['Unnamed: 0', 'Unnamed: 1'], dtype='object')

In [174]:
divipola = divipola.rename(columns={'Unnamed: 0': 'DPTO','Unnamed: 1': 'NOMBRE_DPTO'})

In [176]:
divipola = divipola.drop(index=0)

In [177]:
divipola = divipola[['DPTO','NOMBRE_DPTO']]

In [182]:
base_2025 = pd.merge( base_2025, divipola, on='DPTO',how='left')

In [179]:
[c for c in base_2025.columns if "DPTO" in c]

['DPTO', 'DPTO_y', 'DPTO']

In [180]:
base_2025 = base_2025.loc[:, ~base_2025.columns.duplicated()]
base_2025 = base_2025.drop(columns=['DPTO_y'], errors='ignore')

In [181]:
[c for c in base_2025.columns if "DPTO" in c]

['DPTO']

In [183]:
base_2025[['DPTO','NOMBRE_DPTO']].head()

  DPTO NOMBRE_DPTO
0    8         NaN
1    8         NaN
2    8         NaN
3    8         NaN
4    8         NaN

In [184]:
base_2025.shape

(409127, 322)

**Limpiar columnas duplicadas**

In [185]:
base_2025 = base_2025.loc[:, ~base_2025.columns.str.endswith('_y')]

In [186]:
base_2025.columns = base_2025.columns.str.replace('_x','')

In [187]:
base_2025 = base_2025.loc[:, ~base_2025.columns.duplicated()]

In [188]:
base_2025.shape

(409127, 314)

**Exportar la base final**

In [190]:
base_2025.to_csv('/content/drive/MyDrive/dataset_GEIH/base_GEIH_2025.csv', index=False)